{
 "title": "Condor General View",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CE01 - Slots (15min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "condor_status_machines{ce=\"ce01\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "condor_status_claimed{ce=\"ce01\"}",
     "legendFormat": "Claimed"
    },
    {
     "expr": "condor_status_unclaimed{ce=\"ce01\"}",
     "legendFormat": "Unclaimed"
    }
   ]
  },
  {
   "title": "CE02 - Slots (15 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "condor_status_machines{ce=\"ce02\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "condor_status_claimed{ce=\"ce02\"}",
     "legendFormat": "Claimed"
    },
    {
     "expr": "condor_status_unclaimed{ce=\"ce02\"}",
     "legendFormat": "Unclaimed"
    }
   ]
  },
  {
   "title": "CE01 - Htcondor queue (15min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "condor_queue_held{ce=\"ce01\"}",
     "legendFormat": "Held "
    },
    {
     "expr": "condor_queue_idle{ce=\"ce01\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "condor_queue_running{ce=\"ce01\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "condor_queue_suspended{ce=\"ce01\"}",
     "legendFormat": "Suspended"
    },
    {
     "expr": "condor_queue_removed{ce=\"ce01\"}",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "CE02 - Htcondor queue (15min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "condor_queue_held{ce=\"ce02\"}",
     "legendFormat": "Held "
    },
    {
     "expr": "condor_queue_idle{ce=\"ce02\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "condor_queue_running{ce=\"ce02\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "condor_queue_suspended{ce=\"ce02\"}",
     "legendFormat": "Suspended"
    },
    {
     "expr": "condor_queue_removed{ce=\"ce02\"}",
     "legendFormat": "Removed"
    }
   ]
  }
 ]
}