{
 "title": "Condor General View",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total Running Jobs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(condor_queue_running)", "legendFormat": "Total Running Jobs" }
   ]
  },
  {
   "title": "Total Idle Jobs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    { "expr": "sum(condor_queue_idle)", "legendFormat": "Total Running Jobs" }
   ]
  },
  {
   "title": "Total Queue Held",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    { "expr": "sum(condor_queue_held)" }
   ]
  },
  {
   "title": "Total Queue Suspended",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(condor_queue_suspended)" }
   ]
  },
  {
   "title": "Total Queue Removed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "targets": [
    { "expr": "sum(condor_queue_removed)" }
   ]
  },
  {
   "title": "Total Status Claimed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "sum(condor_status_claimed)" }
   ]
  },
  {
   "title": "LHCb Running Jobs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(condor_queue_running_lhcb)", "legendFormat": "running" }
   ]
  },
  {
   "title": "ALICE Running Jobs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(condor_queue_running_alice)",
     "legendFormat": "running"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 5, "w": 5, "x": 16, "y": 5 } },
  {
   "title": "Total cores",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "targets": [
    { "expr": "sum(condor_status_machines)", "legendFormat": "Available Cores" }
   ]
  },
  {
   "title": "CE01 cores (15 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Max Slots" }
   ],
   "targets": [
    {
     "expr": "condor_status_machines{ce=\"ce01\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "condor_status_claimed{ce=\"ce01\"}",
     "legendFormat": "Claimed"
    },
    {
     "expr": "condor_status_unclaimed{ce=\"ce01\"}",
     "legendFormat": "Unclaimed"
    }
   ]
  },
  {
   "title": "CE02 cores (15 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "condor_status_machines{ce=\"ce02\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "condor_status_claimed{ce=\"ce02\"}",
     "legendFormat": "Claimed"
    },
    {
     "expr": "condor_status_unclaimed{ce=\"ce02\"}",
     "legendFormat": "Unclaimed"
    }
   ]
  },
  {
   "title": "CE03 cores (15 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "condor_status_machines{ce=\"ce03\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "condor_status_claimed{ce=\"ce03\"}",
     "legendFormat": "Claimed"
    },
    {
     "expr": "condor_status_unclaimed{ce=\"ce03\"}",
     "legendFormat": "Unclaimed"
    }
   ]
  },
  {
   "title": "CE01 - Htcondor queue (15min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "condor_queue_held{ce=\"ce01\"}",
     "legendFormat": "Held "
    },
    {
     "expr": "condor_queue_idle{ce=\"ce01\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "condor_queue_running{ce=\"ce01\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "condor_queue_suspended{ce=\"ce01\"}",
     "legendFormat": "Suspended"
    },
    {
     "expr": "condor_queue_removed{ce=\"ce01\"}",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "CE02 - Htcondor queue (15min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "condor_queue_held{ce=\"ce02\"}",
     "legendFormat": "Held "
    },
    {
     "expr": "condor_queue_idle{ce=\"ce02\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "condor_queue_running{ce=\"ce02\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "condor_queue_suspended{ce=\"ce02\"}",
     "legendFormat": "Suspended"
    },
    {
     "expr": "condor_queue_removed{ce=\"ce02\"}",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "CE03 - Htcondor queue (15min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "condor_queue_held{ce=\"ce03\"}",
     "legendFormat": "Held "
    },
    {
     "expr": "condor_queue_idle{ce=\"ce03\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "condor_queue_running{ce=\"ce03\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "condor_queue_suspended{ce=\"ce03\"}",
     "legendFormat": "Suspended"
    },
    {
     "expr": "condor_queue_removed{ce=\"ce03\"}",
     "legendFormat": "Removed"
    }
   ]
  }
 ]
}